# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.2.2.9013
    hooks:
    -   id: style-files
        args: [--style_pkg=styler.mlr, --style_fun=mlr_style]
        additional_dependencies:
        -    mlr-org/styler.mlr
        exclude: 'tests/testthat/.*/.*\.R'
    -   id: roxygenize
        additional_dependencies:
        -    backports
        -    checkmate
        -    curl
        -    data.table
        -    farff
        -    httr
        -    jsonlite
        -    lgr
        -    methods
        -    mlr3
        -    mlr3misc
        -    paradox
        -    progressr
        -    R6
        -    stringi
        -    uuid
        -    xml2
        -    pkgbuild
        -    RWeka
        -    mlr3pipelines
    # codemeta must be above use-tidy-description when both are used
    # -   id: codemeta-description-updated
    -   id: use-tidy-description
    -   id: readme-rmd-rendered
    -   id: parsable-R
    -   id: no-browser-statement
    -   id: deps-in-desc
        args: [--allow_private_imports]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=200']
    -   id: end-of-file-fixer
        exclude: '\.Rd'
-   repo: local
    hooks:
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.Rhistory|\.RData|\.Rds|\.rds$'
        # `exclude: <regex>` to allow committing specific files.

ci:
    autoupdate_schedule: monthly
