// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// parse_arff_levels
Rcpp::StringVector parse_arff_levels(std::string& buffer);
RcppExport SEXP _mlr3oml_parse_arff_levels(SEXP bufferSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string& >::type buffer(bufferSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_arff_levels(buffer));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mlr3oml_parse_arff_levels", (DL_FUNC) &_mlr3oml_parse_arff_levels, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_mlr3oml(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
