# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parse_arff_levels <- function(buffer) {
    .Call('_mlr3oml_parse_arff_levels', PACKAGE = 'mlr3oml', buffer)
}

